version: '3'
services:
  web:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:8000"
    environment:
      - ENVIRONMENT=production
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-mangosteen}
      - POSTGRES_USER=${POSTGRES_USER:-mangosteen}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mangosteen}
  redis:
    image: redis
    container_name: my-redis-container
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mangosteen}
      POSTGRES_USER: ${POSTGRES_USER:-mangosteen}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mangosteen}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
