name: Deploy Docker to Server (No Registry Push)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy project to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT || 22 }}
          source: "."
          target: "~/apps/fastapi-mangosteen-backend"
          rm: true
          overwrite: true
          strip_components: 0
          exclude: ".git,.github/workflows/*,__pycache__/,watch.sqlite*,watch.sqlite-*,*.pyc"

      - name: Build and run on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT || 22 }}
          script: |
            set -euo pipefail
            cd ~/apps/fastapi-mangosteen-backend
            if command -v docker >/dev/null 2>&1; then
              echo "Docker found"
            else
              echo "Docker not installed on server" >&2
              exit 1
            fi
            # Prefer compose if available
            if command -v docker compose >/dev/null 2>&1; then
              if [ -f docker-compose.yml ] || [ -f docker-compose.yaml ]; then
                docker compose up -d --build --remove-orphans
              else
                docker build -t fastapi-mangosteen-backend -f dockerfile .
                docker rm -f fastapi-mangosteen-backend || true
                docker run -d --restart=always --name fastapi-mangosteen-backend -p 8000:8000 fastapi-mangosteen-backend
              fi
            elif command -v docker-compose >/dev/null 2>&1; then
              docker-compose up -d --build --remove-orphans
            else
              docker build -t fastapi-mangosteen-backend -f dockerfile .
              docker rm -f fastapi-mangosteen-backend || true
              docker run -d --restart=always --name fastapi-mangosteen-backend -p 8000:8000 fastapi-mangosteen-backend
            fi
            docker image prune -f || true


